### ISSUE TITLE
Not generatin AP

### ISSUE THREAD

**Issue by zeeshan7860** [s0meguy1/RougeWifi#2] opened 2018-12-27 14:03 UTC
it is stuck at starting hostapd
it is generating AP but not showing captive portal or redirecting to the page

**Comment by reaperNorman** [comment] 2019-10-12 01:10
The problem is that the interface you're trying to run is not in monitor mode.

I fixed this issue by running airmon-ng start {interface}. Then running ./wifi.sh {interface} {internet} {AP name}.

**Comment by james0301** [comment] 2020-01-04 08:53
Sirs can you please help me, i've created the AP but when i connect using my phone, there is no captive porta that pops up. Hope that you can help me

**Comment by s0meguy1** [comment] 2020-12-20 16:20
Closing, not maintaining this anymore

**Closed** 2020-12-20 16:20 UTC
